[package]
name = "pre"
version = "0.1.0"
authors = ["aticu <15schnic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pre-proc-macro = { path = "../proc-macro" }

[dev-dependencies]
trybuild = "1.0"

[features]
#default = ["const-generics-impl"]
default = ["struct-impl"]
struct-impl = ["pre-proc-macro/struct-impl"]
const-generics-impl = ["pre-proc-macro/const-generics-impl"]
